// import { IoLogoGitlab } from 'react-icons/io5'

const ASSETS_BASE_FOLDER_PATH = 'public/assets/'
const PROCESSED_DIRECTORY_NAME = 'processed'

const siteConfig = {
  name: 'Photo',
  nameSuffix: 'blog',
  nameSuffixMatchSize: true,
  get siteTitle() {
    return `Demo ${this.name}${this.nameSuffix}`
  },
  description: 'A statically generated photoblog',
  siteProtocol: 'https',
  siteHostname: 'photoblog.mallocs.net',
  get siteUrl() {
    return `${this.siteProtocol}://${this.siteHostname}`
  },
  sourceUrl: 'https://gitlab.com/mallocs/photoblog-mallocs',
  showSiteIcon: true,
  footerMessage:
    'Generated by NextJS <a href="https://gitlab.com/mallocs/photoblog-mallocs">Photoblog template</a>',
  navbarLinks: [
    {
      name: 'Link 1',
      url: '#link1',
      //    Component: IoLogoGitlab,
    },
    {
      name: 'Link 2',
      url: '#link2',
    },
  ],
  openGraph: {
    imageHeight: 630,
    imageWidth: 1200,
  },
  assetsBaseFolderPath: ASSETS_BASE_FOLDER_PATH,
  slideshowFolderPath: ASSETS_BASE_FOLDER_PATH + 'slideshows',
  slideshowUrlBase: '/assets/' + PROCESSED_DIRECTORY_NAME,
  processedDirectory: ASSETS_BASE_FOLDER_PATH + PROCESSED_DIRECTORY_NAME,
  resizedDirectoryName: 'resized',
  watermarkFile: ASSETS_BASE_FOLDER_PATH + 'watermark.png',
  watermarkOpacity: 0.6,
  saturation: 1.1,
  watermarkSizeRatio: 0.15,
  imageQuality: 75,
  storeFilesInWebP: false,
  blurSize: 40,
  fadeSpeed: 900,
}

export default siteConfig
